### ISSUE TITLE
Undefined method `gateway_options'

### ISSUE THREAD

**Issue by avitus** [spree-contrib/spree_usa_epay#3]
When using the USA_ePay credit card option I get the following error in both production and development environments:

NoMethodError in Spree::CheckoutController#update

undefined method gateway_options for #Spree::Creditcard:0xb3501c44

activemodel (3.2.3) lib/active_model/attribute_methods.rb:407:in method_missing
activerecord (3.2.3) lib/active_record/attribute_methods.rb:148:in method_missing
spree_usa_epay (1.0.2) app/models/spree/gateway/usa_epay.rb:20:in create_profile
spree_core (1.1.1) app/models/spree/payment.rb:94:in create_payment_profile

**Comment by schof** [comment]
Just confirmed this problem with fresh Spree 1.1 install.  Creditcard#gateway_options was removed by @radar a while back in spree core  [47b2884767e4](https://gist.github.com/spree/spree/commit/47b2884767e45fed8f92ecc16e96c72a348e6f50).

**Comment by radar** [comment]
This has been fixed with the above commit. Thanks for letting us know.

**Comment by Ben-M** [comment]
I have the same issue but with Spree 1.1-stable (note: tested only in Development):

NoMethodError (undefined method `gateway_options' for #<Spree::Creditcard:0x007faa945a9628>):
  activemodel (3.2.8) lib/active_model/attribute_methods.rb:407:in`method_missing'
  activerecord (3.2.8) lib/active_record/attribute_methods.rb:149:in `method_missing'
  spree_usa_epay (1.0.2) app/models/spree/gateway/usa_epay.rb:20:in`create_profile'
  /home/ben/.rvm/gems/ruby-1.9.2-head/bundler/gems/spree-03a43e07d5a8/core/app/models/spree/payment.rb:94:in `create_payment_profile'
  activesupport (3.2.8) lib/active_support/callbacks.rb:450:in`block in _run__538729866509819854__save__599603109752658179__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1373'
  state_machine (1.1.2) lib/state_machine/integrations/active_record.rb:480:in`block in around_save'

**Comment by Ben-M** [comment]
I only had gem 'spree_usa_epay' in my gemfile (missing the :git => 'git@github.com:spree/spree_usa_epay.git'), which meant that I was working with an old version from before this commit.

Would a version bump help here?
