### ISSUE TITLE
Mass-assignment error

### ISSUE THREAD

**Issue by avitus** [spree-contrib/spree_usa_epay#4]
When using spree_usa_epay in development environment (Spree 1.1.1, Rails 3.2.3) with USA ePay sandbox account I get the following error:

ActiveModel::MassAssignmentSecurity::Error in Spree::CheckoutController#update

Can't mass-assign protected attributes: gateway_payment_profile_id

activemodel (3.2.3) lib/active_model/mass_assignment_security/sanitizer.rb:48:in `process_removed_attributes'
activemodel (3.2.3) lib/active_model/mass_assignment_security/sanitizer.rb:20:in`debug_protected_attribute_removal'
activemodel (3.2.3) lib/active_model/mass_assignment_security/sanitizer.rb:12:in `sanitize'
activemodel (3.2.3) lib/active_model/mass_assignment_security.rb:230:in`sanitize_for_mass_assignment'
activerecord (3.2.3) lib/active_record/attribute_assignment.rb:75:in `assign_attributes'
activerecord (3.2.3) lib/active_record/persistence.rb:212:in`block in update_attributes'
activerecord (3.2.3) lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
activerecord (3.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
activerecord (3.2.3) lib/active_record/transactions.rb:208:in `transaction'
activerecord (3.2.3) lib/active_record/transactions.rb:293:in`with_transaction_returning_status'
activerecord (3.2.3) lib/active_record/persistence.rb:211:in `update_attributes'
/home/avitus/.rvm/gems/ruby-1.9.2-p290@pariday/bundler/gems/spree_usa_epay-474831845443/app/models/spree/gateway/usa_epay.rb:27:in`create_profile'
spree_core (1.1.1) app/models/spree/payment.rb:94:in `create_payment_profile'

**Comment by GeekOnCoffee** [comment]
@avitus This issue should be resolved in master. Please let us know if it needs to be reopened.
